### ISSUE TITLE
Make appropriate Test on Production

### ISSUE THREAD

**Issue by siteantipas** [Usbac/Wolff#11]
I really do love this like this light framework and the improvements you make each day.
I use it on many projects and **when cloning a new version, working and uploading to production on an online server, some errors serious errors come making me frustrated since I have to wait for you to provide a solution.**
 
That is why I suggest  you deploy the framework on production to test that everything works well, before releasing in on GitHub.

Thank you

**Comment by Usbac** [comment]
Hi @siteantipas!

I'm aware of the errors that happens, I'm sorry. Right now I have made a new commit that changes the framework structure a little, so I don't recommend to update Wolff right now. I'm making a production environment to test that everything will work fine, so this won't happen again.

From now the incoming commits will try to fix any bug or error instead of adding new functionality to the framework. I'll close this issue when the complete stable and error proof version of Wolff came in.

Thanks and regards :)

**Comment by siteantipas** [comment]
Hi @Usbac I'll like to know when you intend finishing this new stable version as I'm planning to use Wolff in  a new project.
Thank you

**Comment by Usbac** [comment]
The first stable version will be finished before the end of the month. 
Since then all the non major changes/commits will be retrocompatible :)

**Comment by siteantipas** [comment]
The issue has not yet been closed as promised for the end of the month. Does that mean you haven't done online tests and bugs corrections yet?

**Comment by Usbac** [comment]
Hi @siteantipas! I have fixed a lot of bugs and structural problems. I'm sorry about the delay, Wolff isn't in the 1.0 version because I was busy with other works, but the current version is quite stable and has been tested on a production environment without problems.

I'll try to commit the 1.0 version during this week, greetings!

**Comment by siteantipas** [comment]
Thank you. I will use version 1.0 in a new project.
