### ISSUE TITLE
Model & Library NOT Found

### ISSUE THREAD

**Issue by siteantipas** [Usbac/Wolff#13]
Hi @Usbac I no longer see the model folder and `$this->load->model()`  and ` $this->load->library()` are no longer valid. These are very **important**  aspects of the framework which makes it ridiculously simple working with databases and external libraries.  I checked on the documentation but couldn't find any help. Can you please elaborate more on that? Thank you.

**Comment by Usbac** [comment]
Hi @siteantipas! Yes, the models and libraries are gone in Wolff, I did this with the intention of making the framework more dynamic and not tie it directly to the MVC pattern. 

But don't worry, you can still make them if you want :)

In this example just add a 'models' folder in the app directory, inside it create a `home.php` file with the following code:

```php
<?php

namespace App\models;

class Home
{
    public function __construct() {
        // Your code
    }
}
```

Then you can load the model in your controller this way:
```php
$model = new \App\models\home();
```

The same can be done with the Libraries creating a 'libraries' folder and so, obviously you can name the classes and folders as you want. You can even make queries in your controllers if it's necessary.

The models where removed on this commit:
https://github.com/Usbac/Wolff/commit/6ca8f5ebcaef8542ac0b2e55e4887472015c05c1

The libraries where removed on this commit:
https://github.com/Usbac/Wolff/commit/722a1ec1cb2c505c2c09289a2cbfa736282cd9b3

In the wiki there's no explanation about how to create custom classes because I'm working on it right now, I'm sorry about that detail. 
Thank you and regards :)

**Comment by siteantipas** [comment]
Oh yeah, it works. Thank you
