### ISSUE TITLE
Error problem 

### ISSUE THREAD

**Issue by smartyoon** [Usbac/wolff#26]
Using version 3.0

Error problem after first installation
I guess it's like a cache problem
Please tell me how to solve
404
{{ $lang['msg'] }}

**Comment by Usbac** [comment]
Hello @smartyoon! Could you please give me more details about the problem? Like the environment, PHP version or if you were using Apache instead of PHP built-in server.

Also the problem is that a 404 page is displayed instead of the welcome page, right?

Regards!

**Comment by Paynmayn** [comment]
Same happens here (404 page instead of the welcome page) on Windows (XAMPP 7.4.5).
Clean install through composer (also tried with the bundle).
It doesn't include the subfolder in the style.css URL either (uses "http://localhost/assets/css/styles.css" instead of "http://localhost/wolff/assets/css/styles.css").

Windows 10
Apache 2.4
PHP 7.4

None of these problems on a linux server with Apache 2.4 and PHP 7.4.

**Comment by Usbac** [comment]
Hello @Paynmayn and @smartyoon! I'm glad to announce that the problem has been fixed for the version `3.0.2`.

https://github.com/Usbac/wolff-framework/commit/fdd042198d6c8357ebb87a2d1d9f3a05e00f6f5c.

Thank you so much for your contribution. 
Regards! :)
