### ISSUE TITLE
template extends errors

### ISSUE THREAD

**Issue by wfsdaj** [Usbac/wolff#38]
![image](https://user-images.githubusercontent.com/36911167/127996574-11f7a32a-1a45-4dd0-a54f-ea28f33c4aac.png)

![image](https://user-images.githubusercontent.com/36911167/127996614-4bcf2ab2-5ac1-4475-a306-47180ec6d489.png)

![image](https://user-images.githubusercontent.com/36911167/127996691-7d5023f0-96d7-4d2a-8ce7-d9baf0dbcfb5.png)

**Comment by Usbac** [comment]
Thank you for pointing that out! 😄 It has been fixed in the new version [4.0.3](../releases/tag/v4.0.3).

You can run `composer update` to get the new version. If you want to fix it without updating Wolff, just be sure to add a whitespace character after the endblock tag, like this `{[ endblock ]} </title>`.

Regards!
