### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'System\Route' not found 

### ISSUE THREAD

**Issue by siteantipas** [Usbac/Wolff#7]
Hi everyone. I wonder if any of you have successfully hosted a **Wolff**  project to the production server 
As for me, I get the error `PHP Fatal error:  Uncaught Error: Class 'System\Route' not found in /home1/.../system/routes.php:5` when I upload to a production server.

The project was actually working very wll on localhost with no PHP errors.

![Capture](https://user-images.githubusercontent.com/24583854/54475361-aa83d380-47f0-11e9-9122-c6f1969079e1.PNG)

**Comment by Usbac** [comment]
Hi! This problem is due to your server system (which I suppose is Linux) being case sensitive with the filename. In windows there is not difference between Route.php and route.php, but in Linux systems there is a difference. 
I will put the first letter in uppercase for all the files in the next commit.

Meanwhile a solution could be renaming your system/route.php file to system/Route.php. Let me know if this help you :)

**Comment by Usbac** [comment]
Fixed #7 :)
